CREATE TABLE paciente (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(80) NOT NULL,
    cpf VARCHAR(50) NOT NULL,
    telefone VARCHAR(50) NOT NULL,
    email VARCHAR(50)NOT NULL,
    logradouro VARCHAR(80) NOT NULL,
    numero BIGINT(20) NOT NULL, 
    complemento VARCHAR(50), 
    cep VARCHAR(10) NOT NULL,
    cidade_uf VARCHAR(50) NOT NULL
   
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE medico (
    id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(80) NOT NULL,
    crm VARCHAR(10) NOT NULL,
   	tipo_especialista VARCHAR(50) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(20) NOT NULL    
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

